# Generated by Django 5.1.7 on 2025-04-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="null", max_length=300),
        ),
    ]
